Create new TCRseq assay and FASTQ template
CIMAC-CIDC/cidc-schemas pull request #364
Opened 2020-08-27 22:49 UTC by roshni-b

2020-09-15 19:10 UTC, curlup requested changes

2020-09-15 19:10 UTC, curlup commented on tests/prism/cidc_test_data/assay_data.py
> +            metadata_availability=None,
```suggestion
            metadata_availability=False,
```

2020-09-15 19:10 UTC, curlup commented on tests/prism/cidc_test_data/assay_data.py
> +            metadata_availability=None,
```suggestion
            metadata_availability=False,
```

2020-09-15 19:10 UTC, curlup commented on tests/prism/cidc_test_data/assay_data.py
> +            metadata_availability=None,
```suggestion
            metadata_availability=False,
```

2020-09-15 19:10 UTC, curlup commented on tests/prism/cidc_test_data/assay_data.py
> +            metadata_availability=None,
```suggestion
            metadata_availability=False,
```

2020-09-15 19:10 UTC, curlup commented on tests/prism/cidc_test_data/assay_data.py
> +            metadata_availability=None,
```suggestion
            metadata_availability=False,
```

2020-09-15 19:10 UTC, curlup commented on tests/prism/cidc_test_data/assay_data.py
> +            metadata_availability=None,
```suggestion
            metadata_availability=False,
```

2020-09-29 15:37 UTC, curlup requested changes
Hey, nice! Starts to pan out

the only thing is this `files` to `read_files` rename, I think you'd need to
* either write a data model migration as here https://github.com/CIMAC-CIDC/cidc-schemas/blob/master/cidc_schemas/migrations.py#L103 This will be an incompatible DM change so I'd suggest also changing version to `0.21.0` and you'll need to add API migration that uses that when you roll that out.
* or maybe change `fastq_pair_or_bam.json` to allow not only `(r1 + r2) or bam` but allow additional fields and then create `reads_with_index.json` based on that, that will allow to add needed index files. (I would suggest in that case renaming `fastq_pair_or_bam.json` to something with `core` or `base` in the name)

2020-09-29 15:37 UTC, curlup commented on cidc_schemas/schemas/assays/components/ngs/rna/rna_entry.json
> +    "read_files": {"$ref": "assays/components/ngs/ngs_assay_record.json#properties/read_files"}
why do you need to change that? This will require migrating all the production (not to mention staging) rna assay metadata in `trial_metadata.metadata_json`
I would suggest not do that without a really strong reason for.

2020-09-29 15:37 UTC, curlup commented on cidc_schemas/schemas/assays/components/ngs/ngs_assay_record.json
> +    "index_files": {
I would not add `index_files` here, as we probably don't want to make `index_files` required for some ngs assay

2020-09-29 15:37 UTC, curlup commented on cidc_schemas/schemas/assays/components/ngs/tcr/tcr_entry.json
> +    "sequencing_run_date": {
just double checking - can seq run date be different between samples within one batch? if not, this should be put in `tcr_assay.json` along side with `batch_id`

2020-10-06 18:23 UTC, curlup requested changes
overall looks good, DM more or less makes sense together with the template. 
though, there are some mis-alignments and ambiguities, that need to be resolved.

2020-10-06 18:23 UTC, curlup commented on cidc_schemas/schemas/assays/components/ngs/tcr/tcr_entry.json
> -  "mergeStrategy": "objectMerge"
why is this removed?

2020-10-06 18:23 UTC, curlup commented on cidc_schemas/schemas/assays/components/ngs/tcr/tcr_entry.json
> +    "files": {"$ref": "assays/components/ngs/tcr/tcr_input.json"}
I think you'll have to list all the props from `ngs_assay_record.json` explicitly here

2020-10-06 18:23 UTC, curlup commented on cidc_schemas/schemas/assays/components/ngs/tcr/tcr_input.json
> +      "$ref": "artifacts/artifact_csv.json"
hm, could you please elaborate, how is this a part of an `input`? is it not a csv we need to generate based on samples metadata, as `metasheet.csv` is for rna?

2020-10-06 18:23 UTC, curlup commented on cidc_schemas/schemas/assays/components/ngs/tcr/tcr_replicates.json
> +    "rna_quantity_ng": {
duplicated in the `tcr_input.json` json above, I don't think we need it two times

2020-10-06 18:23 UTC, curlup commented on cidc_schemas/schemas/assays/components/ngs/tcr/tcr_replicates.json
> +    "i2": {"$ref": "assays/components/reads_with_index.json#properties/i2"}
shouldn't this schema the inherit from `reads_with_index.json` then?

2020-10-06 18:23 UTC, curlup commented on cidc_schemas/schemas/assays/components/reads_with_index.json
> +  ],
whenever a model "inherits" from another one (with `allOf`) all the props of the parent need to be list in the child explicitly.

2020-10-06 18:23 UTC, curlup commented on cidc_schemas/schemas/assays/components/reads_with_index.json
> +      "type": "array",
`"type": "array"` - does it mean there will be many index files per replicate? My understanding was that it will be just one (well, two) the same way as with read r1/r2 in wes/rna.

2020-10-06 18:23 UTC, curlup commented on cidc_schemas/schemas/assays/tcr_assay.json
> +    "batch_id"
```suggestion
    "batch_id",
    "sequencing_run_date"
```

2020-10-06 18:23 UTC, curlup commented on cidc_schemas/schemas/assays/components/ngs/tcr/tcr_input.json
> +      "$ref": "artifacts/artifact_csv.json"
also apart from that, do we expect to get a (different) `sample_sheet.csv` for each sample/cimac_id?

2020-10-06 18:23 UTC, curlup commented on cidc_schemas/schemas/templates/metadata/tcr_fastq_template.json
> +            "merge_pointer": "0/sample_sheet",
yeah, this is mis-aligned with what you have in the DM - there it's a sample_sheet per sample, which doesn't make sense to me.

2020-10-06 18:23 UTC, curlup commented on cidc_schemas/schemas/templates/metadata/tcr_fastq_template.json
> +        "prism_data_object_pointer" : "/records/-",
I think it conflicts with line 38 in this file and should be removed
```suggestion
```

2020-10-06 18:23 UTC, curlup commented on template_examples/csvs/tcr_fastq_template__TCR.csv
> +"#d","CTTTPP111.00","1","/local/path/to/read1_1.fastq.gz","/local/path/to/read2_1.fastq.gz","/local/path/to/index1_1.fastq.gz","/local/path/to/index2_1.fastq.gz","600"
maybe would be cool to add a sample with more than one replicate here, to illustrate the intent better.

2020-10-06 23:25 UTC, roshni-b commented on cidc_schemas/schemas/assays/components/ngs/tcr/tcr_input.json
> +      "$ref": "artifacts/artifact_csv.json"
This sample_sheet is part of `input` and different from what we generate for RNA. This file is ingested part of MiSeq assay data. It should be 1 sample_sheet.csv per batch, not per CIMAC ID.

2020-10-07 11:26 UTC, roshni-b commented on cidc_schemas/schemas/assays/components/ngs/tcr/tcr_entry.json
> +    "files": {"$ref": "assays/components/ngs/tcr/tcr_input.json"}
cimac_id and files are the only 2 props in `ngs_assay_record.json`, can you elaborate what more to list here?

2020-10-07 11:33 UTC, roshni-b commented on cidc_schemas/schemas/templates/metadata/tcr_fastq_template.json
> +            "merge_pointer": "0/sample_sheet",
What is the appropriate place for sample_sheet to be defined, if not `tcr_input.json`?

2020-10-07 15:26 UTC, roshni-b commented on cidc_schemas/schemas/assays/components/reads_with_index.json
> +      "type": "array",
Yes, there will be 2 index files per replicate. The way r1/r2 is defined, in reads_core.json, is `"type": "array"`. Hence I'd similarly set the type of i1, i2 to mirror that. Should they all not be arrays then?

2020-10-07 15:27 UTC, roshni-b commented on template_examples/csvs/tcr_fastq_template__TCR.csv
> +"#d","CTTTPP111.00","1","/local/path/to/read1_1.fastq.gz","/local/path/to/read2_1.fastq.gz","/local/path/to/index1_1.fastq.gz","/local/path/to/index2_1.fastq.gz","600"
Will do, once I clear up some of these errors

2020-10-08 18:28 UTC, jacoblurye commented on tests/data/clinicaltrial_examples/CT_1.json
> +              "replicates": {
This value should be an array, and that's causing tests to fail.

2020-10-09 18:13 UTC, curlup commented on cidc_schemas/schemas/templates/metadata/tcr_fastq_template.json
> +        "prism_data_object_pointer": "/records/0/files/replicates/-",
```suggestion
        "prism_data_object_pointer": "/records/0/files/replicates/0/",
```

2020-10-10 17:53 UTC, roshni-b commented on cidc_schemas/schemas/templates/metadata/tcr_fastq_template.json
> +        "prism_data_object_pointer": "/records/0/files/replicates/-",
This change eliminates 'type_changes' but introduces another key 'iterable_item_removed' to the DeepDiff between expected and received patches.

2020-10-13 17:23 UTC, curlup approved these changes

2020-10-13 17:23 UTC, curlup commented on cidc_schemas/__init__.py
> +__version__ = "0.20.8"
```suggestion
__version__ = "0.21.0"
```

2020-10-13 17:24 UTC, curlup commented on cidc_schemas/__init__.py
> +__version__ = "0.20.8"
so whenever we'll have tcr data in, we won't revert that version without a second thought.

2020-10-13 17:42 UTC, merged