Autogeneration of templates from cidc-ngs-pipeline-api output_API.json's
CIMAC-CIDC/cidc-schemas pull request #378
Opened 2020-10-21 20:01 UTC by scvannost

Big PR, let me know your questions

Also willing to go over it via video

2020-10-21 21:01 UTC, jacoblurye reviewed
Haven't been able to review nearly the whole PR yet, but here are a couple comments on the first part I took a look at!

2020-10-21 21:05 UTC, scvannost commented on cidc_schemas/template.py
> +def convert_all_apis(test: bool = False):
changed! good suggestions

2020-10-21 21:06 UTC, scvannost commented on cidc_schemas/template.py
> +            continue
it would still attempt to save it though without this, though I could instead put that in the `else` of the `try`

2020-10-21 21:08 UTC, scvannost commented on cidc_schemas/template.py
> +    from cidc_ngs_pipeline_api import SCHEMAS as to_convert
fixed in next commit

2020-10-21 21:09 UTC, scvannost commented on cidc_schemas/template.py
> +        ret = {}
It's possible, I'll look into it

monkeypatch `TEMPLATE_DIR` or something...

2020-10-21 21:15 UTC, scvannost commented on cidc_schemas/template.py
> +        # try to convert it, but skip if it's not implemented'
if an output_API has been added to ngs-pipeline-api without its component schemas being added to `schemas/assays/components/ngs/...`, I don't feel that it should fail on converting the ones that it can.

see the PR on `cidc-api-gae` where the app calls this on initialization, so throwing an uncaught error on the whole system for an extra output_API seems overkill

2020-10-22 13:06 UTC, jacoblurye commented on cidc_schemas/template.py
> +        ret = {}
I don't think monkeypatch is what you'll need. Check out how this test uses the [`tmpdir`](https://docs.pytest.org/en/stable/tmpdir.html) fixture: https://github.com/CIMAC-CIDC/cidc-schemas/blob/2c1db33c21efaa9a71d00b3c88bda9073134dd67/tests/test_templates.py#L52

2020-10-22 13:09 UTC, jacoblurye commented on cidc_schemas/template.py
> +            continue
Oh, my bad - I totally misread the code here! You're 100% right.

2020-10-22 13:13 UTC, jacoblurye commented on cidc_schemas/template.py
> +        # try to convert it, but skip if it's not implemented'
Gotcha, works for me. Maybe instead of printing out the error, the `print` statement can say something like `print(f"skipping {analysis} - template schema generator not yet implemented")`, since it's not an error, but rather a possibility we've accounted for.

2020-10-22 14:11 UTC, scvannost commented on cidc_schemas/template.py
> +        # try to convert it, but skip if it's not implemented'
addressed in next commit

2020-10-22 14:35 UTC, scvannost commented on cidc_schemas/template.py
> +                path[1:] if len(path) > 1 else [],
yes, yes it is

2020-10-22 14:39 UTC, scvannost commented on cidc_schemas/template.py
> +            trial.extend(path[1:])
good catch

2020-10-22 14:39 UTC, scvannost commented on cidc_schemas/template.py
> +                path[1:] if len(path) > 1 else [],
address in next commit

2020-10-22 14:40 UTC, scvannost commented on cidc_schemas/template.py
> +    if not ret[0] and "." in path[0]:
addressed in next commit by changing initialization to `('',[],{})`

2020-10-22 15:43 UTC, scvannost commented on cidc_schemas/template.py
> +        ret = {}
addressed in commit 'Suite of minor changes'

2020-10-22 20:26 UTC, jacoblurye commented on cidc_schemas/template.py
> +    file_path = file_path.replace("//", "/").replace("--", "_")
Hmm, the intended functionality here strikes me as pretty similar to what we already do to calculate `facet_group`s here: https://github.com/CIMAC-CIDC/cidc-schemas/blob/4a8ae7b37947001fd8a48489a590248ec09d7862/cidc_schemas/template.py#L303
Could calling that function on `file_path` work instead?

2020-10-22 20:26 UTC, jacoblurye commented on cidc_schemas/template.py
> +    merge_pointer += "/" + curr_step
```suggestion
    curr_step, file_path, curr_context = _first_in_context(file_path, context)
    merge_pointer = "0/" + curr_step
```

2020-10-22 20:26 UTC, jacoblurye commented on cidc_schemas/template.py
> +        file_path = file_path[1:]
Is there a reason why some file path adjustments happen here and others happen in the body of `_first_in_context`?

2020-10-22 20:26 UTC, jacoblurye commented on cidc_schemas/template.py
> +    return merge_pointer
If no paths in `curr_context` match `file_path`, we could end up with `merge_pointer == "0/"` here. Maybe we should raise an error in this case, since we want to find a match for every `file_path` (right?).

2020-10-22 21:18 UTC, scvannost commented on cidc_schemas/template.py
> +    file_path = file_path.replace("//", "/").replace("--", "_")
`file_path` is not a lambda, so it would always use the `except`
then there would still be `.` and `_` that would need to be removed internally, and there's still the `replace("--", "_")`

I don't think either is really better, but it is a close reimplementation

2020-10-22 21:21 UTC, scvannost commented on cidc_schemas/template.py
> +        file_path = file_path[1:]
currently `_first_in_context` is recursive, so having it here means it only runs once, but you still get the benefits of recursion

2020-10-22 23:43 UTC, jacoblurye reviewed
Definitely worth getting @curlup's feedback before merging since this is such a big one, so I'll hold off on approving. Kudos for wading through all this complexity.

Also, just to double check my overall understanding: this allows biofx folks to change the local file paths for files that we already include in the data model, but it won't allow them to add new pipeline output files to the data model. Right?

2020-10-22 23:43 UTC, jacoblurye commented on cidc_schemas/template.py
> +    ret = ""
unused

2020-10-22 23:43 UTC, jacoblurye commented on cidc_schemas/template.py
> +        file = "_".join(file[:-n])
Here's a way you can simplify this block of code (tests pass, so I think it's all good?):
```python
   # (use a set instead of a list, since that'll inclusion make checks quicker below)
   possible_exts = {
        "tsv",
        "log",
        # ...
        "sf",
    }

    # trim off extension from file path
    file_parts = file.split("_")
    while file_parts[-1] in possible_exts:
        file_parts.pop()
    file = "_".join(file_parts)
```

2020-10-22 23:43 UTC, jacoblurye commented on cidc_schemas/template.py
> +            possible_exts = [
Since this is duplicated from `_calc_gcs_uri` above, I'd pull this value out of both functions to be a shared constant.

2020-10-22 23:43 UTC, jacoblurye commented on cidc_schemas/template.py
> +def _convert_api_to_template(name: str, schema: dict):
Agreed re: complexity 😅 Not so sure how to make things less complex, though, given all the different corner cases that arise from those pre-existing naming inconsistencies.

2020-10-22 23:43 UTC, jacoblurye commented on requirements.txt
> +pyyaml>=5.1
`~=` is safer than `>=`, since this allows `pyyaml==5.*` but not `pyyaml==6.*` (and a major version bump generally means breaking changes).

2020-10-22 23:43 UTC, jacoblurye commented on tests/test_template.py
> +def test_first_in_context():
Nice test! It documents what `_first_in_context` does really clearly.

2020-10-23 15:21 UTC, scvannost commented on cidc_schemas/template.py
> +        file = "_".join(file[:-n])
I totally forgot `pop` existed tbh

2020-10-23 15:25 UTC, scvannost commented on tests/test_template.py
> +def test_first_in_context():
Thanks!

2020-10-23 15:32 UTC, scvannost commented
> Definitely worth getting @curlup's feedback before merging since this is such a big one, so I'll hold off on approving. Kudos for wading through all this complexity.
> 
> Also, just to double check my overall understanding: this allows biofx folks to change the local file paths for files that we already include in the data model, but it won't allow them to add new pipeline output files to the data model. Right?

Yes!

They could even push new/highly modified output_APIs that would break against the data model, then we once the data model is updated we change the version of ngs-pipeline-apis this is dependent on and it will generate the new template for us.

2020-10-23 16:28 UTC, curlup commented on cidc_schemas/template.py
> +    return merge_pointer
I think explicitly erroring is better than silently swallowing a non-mergeable entry.

2020-10-23 16:28 UTC, curlup commented on cidc_schemas/__init__.py
> +__version__ = "0.21.2"
oh, I don't think that's a minor thing)

2020-10-23 17:43 UTC, scvannost commented on cidc_schemas/__init__.py
> +__version__ = "0.21.2"
haha okay

2020-10-28 14:43 UTC, curlup reviewed
I still need to go through the second part - actual generated templates etc.

2020-10-28 14:43 UTC, curlup commented on cidc_schemas/template.py
> +    return merge_pointer
is it covered with tests to check that it throughs error for "bad" merge_pointer?

2020-10-28 14:43 UTC, curlup commented on cidc_schemas/template.py
> +def _convert_api_to_template(name: str, schema: dict):
+1

2020-10-28 14:43 UTC, curlup commented on cidc_schemas/template.py
> +        # so many ways to write this too
extract this into a separate `_per_entry_convert` maybe?

2020-10-28 14:43 UTC, curlup commented on cidc_schemas/template.py
> +            for ptr in merge_pointer.lstrip("0/"):
I'm lost here: is `ptr` takes each char in merge_pointer then?

2020-10-28 14:43 UTC, curlup commented on cidc_schemas/template.py
> +                raise InvalidMergeTargetException(f"{file_path} cannot be mapped to a location of the data object")
I think this should be raised not here but where it's first calculated.

2020-10-28 14:43 UTC, curlup commented on cidc_schemas/template.py
> +                raise InvalidMergeTargetException(f"{file_path} is not the correct format for inferred merge target {merge_pointer}")
also extract into a helper, something like `_calc_gcs_...`?

2020-10-28 14:54 UTC, scvannost commented on cidc_schemas/template.py
> +        "prism_template_root_object_schema": f"assays/components/ngs/{name}/{'rnaseq' if name == 'rna' else name}_analysis.json",
see this branch for exactly that: https://github.com/CIMAC-CIDC/cidc-schemas/compare/autotemplates...consistency

2020-10-28 15:00 UTC, scvannost commented on cidc_schemas/template.py
> +        file_path = temp[0] + temp[1].split("}", 1)[1].strip("._")
it's possible yeah. i did it this way to avoid having to drop more `.` and `_` later, which I'm doing with the `strip("._")` here

2020-10-28 15:41 UTC, scvannost commented on cidc_schemas/template.py
> +        # so many ways to write this too
they share a lot of information across different runs through this loop
namely: `used_merge_pointers` and `used_gcs_uris`, `assay_schema`, and `name`

with the individual `long_key : entries` as additional parameters, `_per_entry_convert` would have 6 parameters
I'm not sure that would be more clear

2020-10-28 15:46 UTC, scvannost commented on cidc_schemas/template.py
> +            for ptr in merge_pointer.lstrip("0/"):
forgot to split it by `/` to get each level of the pointer individually

2020-10-28 17:12 UTC, scvannost commented on cidc_schemas/template.py
> +                raise InvalidMergeTargetException(f"{file_path} is not the correct format for inferred merge target {merge_pointer}")
similar to the other, this would require `short_key`, `long_key`, `name`, `merge_pointer`, and `entry["file_path_template"]`
I'm not sure that 5 parameters would be more clear

2020-10-28 17:18 UTC, scvannost commented on cidc_schemas/template.py
> +            ret = (path[0], [], context[path[0]]["properties"])  # path[1:] == []
added handling for arrays

2020-10-28 17:18 UTC, scvannost commented on cidc_schemas/template.py
> +                raise InvalidMergeTargetException(f"{file_path} cannot be mapped to a location of the data object")
moved

2020-10-28 18:24 UTC, curlup commented on cidc_schemas/template.py
> +        "prism_template_root_object_schema": f"assays/components/ngs/{name}/{'rnaseq' if name == 'rna' else name}_analysis.json",
sweet

2020-10-28 18:25 UTC, curlup commented on cidc_schemas/template.py
> +        file_path = temp[0] + temp[1].split("}", 1)[1].strip("._")
eh, not sure what you mean

2020-10-28 18:27 UTC, curlup commented on cidc_schemas/template.py
> +            for ptr in merge_pointer.lstrip("0/"):
that brings me to the question: how good is this all covered with tests? Somehow I don't see coverage stats here

2020-10-29 19:55 UTC, curlup commented on cidc_schemas/template.py
> +        except NotImplementedError as e:
I can see how `NotImplementedError` might (after some changes) become throwable not only in case of not supported analysis. So I'd suggest changing this to explicit check if `analysis` is supported and not catching `NotImplementedError` so it can fail on that.

2020-10-29 19:55 UTC, curlup commented on cidc_schemas/template.py
> +                json.dump(template, f)
how do you see we approach this regeneration?
- on every build
- on every commit
- manually? I don't like manually because it gets skipped (see how we forget to generate docs all the time, but docs are not that important as templates are)

2020-10-29 19:55 UTC, curlup commented on cidc_schemas/template.py
> +                    # to handle arrays
so code climate shows that array handling is not covered during unit tests.

2020-10-29 19:55 UTC, curlup commented on cidc_schemas/template.py
> +                file_path[-1] = ".".join(temp[-2:] + temp[:-2])
btw do you have codeclimate browser plugin to see per line test coverage? this one is not covered. Is it used at all then?

2020-10-29 19:55 UTC, curlup commented on cidc_schemas/template.py
> +            else long_key.replace(" ", "_")
that's hard to read

2020-10-29 19:55 UTC, curlup commented on cidc_schemas/template.py
> +            else "sample.json#properties/cimac_id",
nitpick but I think that asks for a restructuring, as is now - hard to comprehend

2020-10-29 19:55 UTC, curlup commented on cidc_schemas/template.py
> +            ]  # only keep valid parts, in order they appear
does the `black` makes it formatted like this?

2020-10-29 19:55 UTC, curlup commented on tests/data/schemas/target-templates/rna_template.json
> +{
why does this not show as a diff with current template?

2020-10-29 19:55 UTC, curlup commented on tests/data/schemas/target-templates/wes_template.json
> +{
same here - I would like to see here in the PR the diff between what we had vs what's been generated. is it possible?

2020-10-29 19:55 UTC, curlup commented on tests/test_template.py
> +    rna_output = _convert_api_to_template("rna", rna_api)
I'd suggest to split the test, those two assays are not directly related in the test code AFAIK?

2020-10-29 20:38 UTC, scvannost commented on cidc_schemas/template.py
> +                json.dump(template, f)
right now I also have a PR against cidc-api-gae that will run it every time the app boots?

2020-10-29 20:39 UTC, scvannost commented on cidc_schemas/template.py
> +                file_path[-1] = ".".join(temp[-2:] + temp[:-2])
I believe it was used when I was trying to be smarter about generating the categories etc. not needed now seemingly

2020-10-29 20:39 UTC, scvannost commented on cidc_schemas/template.py
> +            ]  # only keep valid parts, in order they appear
yes it does

2020-10-29 20:39 UTC, scvannost commented on tests/test_template.py
> +    rna_output = _convert_api_to_template("rna", rna_api)
no they are not, just testing the same functionality so I figured why not put them together

2020-10-29 20:53 UTC, scvannost commented on cidc_schemas/template.py
> +        except NotImplementedError as e:
addressed by moving loading analysis schema to this function and catching any exception from `_load_dont_validate_schema` with same print/skip as already here

any NotImplementErrors thrown will be correctly raised

2020-10-29 21:12 UTC, scvannost commented on tests/test_template.py
> +    rna_output = _convert_api_to_template("rna", rna_api)
split in next commit

2020-10-29 21:15 UTC, scvannost commented on cidc_schemas/template.py
> +                    # to handle arrays
added explicit checking for this to `test_first_in_context`

2020-10-29 21:15 UTC, scvannost commented on cidc_schemas/template.py
> +            else long_key.replace(" ", "_")
fixed in next commit

2020-10-29 21:15 UTC, scvannost commented on cidc_schemas/template.py
> +            else "sample.json#properties/cimac_id",
fixed in next commit

2020-10-29 21:19 UTC, scvannost commented on cidc_schemas/template.py
> +                file_path[-1] = ".".join(temp[-2:] + temp[:-2])
these are all covered in `test_generate_analysis_template_schemas` (now split into `_rna` and `_wes`) by rederiving the entired template schema

2020-10-29 21:20 UTC, scvannost commented on tests/data/schemas/target-templates/rna_template.json
> +{
the current code generates exactly the template schema that was there before
`test_generate_analysis_template_schemas` (now split into `_rna` and `_wes`) checks this, using original files as target and asserting no differences

2020-10-29 21:20 UTC, scvannost commented on tests/data/schemas/target-templates/wes_template.json
> +{
see `rna_template.json`

2020-10-30 19:57 UTC, curlup commented on cidc_schemas/template.py
> +                json.dump(template, f)
I'm not sure about generation on app boot. I'd say schemas build (it's a package after all) should be fully tested and not potentially throwing something on app start.

What do you think on doin it on commit (and automatically adding everything generated to the commit) - as we do we `xxx.csv` out of `xx_example.xslx` generation? 
this at least will make all the changes visible in the diffs / PRs. 
though it doesn't quite help with when one wants to update pipeline dependency and update the DM accordingly or vice versa.

2020-10-30 20:00 UTC, curlup commented on tests/data/schemas/target-templates/rna_template.json
> +{
hm. right, i see how it was helpful while developing. but I don't think that's what we want going forward? 

consider if we were to merge Len's WES PR in the pipelines? it would generate new template.json, break the test, won't it? and that's not what we want - we probably want to just use the newly generated one.

2020-10-30 20:20 UTC, scvannost commented on cidc_schemas/template.py
> +                json.dump(template, f)
that seems good

yeah, that would just move versioning issues to versions of cidc-schemas imported by eg the api

2020-10-30 20:23 UTC, scvannost commented on tests/data/schemas/target-templates/rna_template.json
> +{
fair, that also affects testing as I'd have to test a lot more things using dummy examples, or at least include dummy output_APIs to check that it can still generate the original template.json

2020-11-03 15:23 UTC, curlup commented
@scvannost any plans on pre-commit stuff, or is it already here? 

if you don't want to overwrite `{pipeline}_analysis_template.json` with autogenerated ones, I'd suggest rename old ones to be used only in tests or something

2020-11-03 15:55 UTC, curlup requested changes

2020-11-03 15:55 UTC, curlup commented on cidc_schemas/schemas/templates/analyses/wes_analysis_template.json
> +{"title": "WES analysis template", "description": "Metadata information for WES Analysis output.", "prism_template_root_object_schema": "assays/components/ngs/wes/wes_analysis.json", "prism_template_
nah, I think this should be pretty printed

2020-11-03 16:02 UTC, scvannost commented on cidc_schemas/schemas/templates/analyses/wes_analysis_template.json
> +{"title": "WES analysis template", "description": "Metadata information for WES Analysis output.", "prism_template_root_object_schema": "assays/components/ngs/wes/wes_analysis.json", "prism_template_
handled in next commit

2020-11-17 18:50 UTC, curlup approved these changes

2020-11-17 18:58 UTC, merged