Create new TCRseq analysis template
CIMAC-CIDC/cidc-schemas pull request #380
Opened 2020-10-23 12:16 UTC by roshni-b

2020-10-23 16:45 UTC, curlup commented on cidc_schemas/schemas/assays/components/ngs/tcr/tcr_analysis.json
> +    "additionalProperties": true,
this should be false.

2020-10-26 18:18 UTC, roshni-b commented on tests/prism/cidc_test_data/analysis_data.py
> +        "assays": {
This was intended implementation, to simplify `combined_batches` if you take a look above at CyTOF analysis, it was also this way. Do you want me to change it?

2020-10-26 18:32 UTC, roshni-b commented on cidc_schemas/schemas/assays/tcr_assay.json
> -    "sample_sheet"
This was intended, we weren't sure whether the `Sample Sheet` and `Summary_Info` files are going to be available for future runs, hence.

2020-10-26 19:20 UTC, curlup commented on tests/prism/cidc_test_data/analysis_data.py
> +        "assays": {
not sure I understand the answer.

2020-10-29 21:31 UTC, curlup requested changes
if i'm not mistaken, needs a layer allowing for multiple batches. 

please revert any changes to the assay part of the DM

2020-10-29 21:31 UTC, curlup commented on cidc_schemas/schemas/assays/components/available_ngs_analyses.json
> +      "$ref": "assays/components/ngs/tcr/tcr_analysis.json"
i guess there should be a layer of per batch analysis, as in rna https://github.com/CIMAC-CIDC/cidc-schemas/blob/master/cidc_schemas/schemas/assays/components/ngs/rna/rnaseq_analysis.json

because as is it won't allow to ingest more than 1 batch of analysis. And this is not how we expect it should be, right?

2020-10-29 21:31 UTC, curlup commented on cidc_schemas/schemas/assays/tcr_assay.json
> +    "summary_info": {
summary_info moved to analysis, needs to be removed here

2020-10-29 21:31 UTC, curlup commented on cidc_schemas/schemas/assays/components/ngs/tcr/tcr_pair_analysis.json
> +    "additionalProperties": true,
this should not be `true`. (I need to fix strict schema to better point this out)

2020-10-29 21:31 UTC, curlup commented on cidc_schemas/schemas/assays/tcr_assay.json
> +    "summary_info": {
if all that reformatting is unrelated, can we maybe revert it, so blame will point to related commits ?

2020-10-29 21:31 UTC, curlup commented on cidc_schemas/schemas/assays/tcr_assay.json
> -    "sample_sheet"
I think `sample_sheet` should be required, as for now there isn't a template that will not ask for sample sheet. 
overall I think this PR should not touch assay part of the DM

2020-10-29 21:31 UTC, curlup commented on cidc_schemas/schemas/templates/analyses/tcr_analysis_template.json
> +                            "type_ref": "assays/components/local_file.json#properties/file_path",
or, we're getting only two artifacts per sample. pretty simple! I like it.

2020-10-30 19:01 UTC, scvannost commented on cidc_schemas/schemas/assays/tcr_assay.json
> -    "sample_sheet"
put back in next commit

2020-11-02 19:59 UTC, curlup approved these changes
I would still suggest to merge the consistency branch first - we'll see it builds then do this thing

2020-11-06 18:02 UTC, merged