Remove brackets from generated gcs-uri
CIMAC-CIDC/cidc-schemas pull request #402
Opened 2020-12-15 21:16 UTC by scvannost

2020-12-15 21:18 UTC, scvannost commented
See https://github.com/CIMAC-CIDC/cidc-cli/pull/134

2020-12-15 21:48 UTC, jacoblurye requested changes

2020-12-15 21:48 UTC, jacoblurye commented on cidc_schemas/template.py
> +
Instead of removing these on the fly, I'd rather see this encoded as a regex constraint on the `object_url` field: https://github.com/CIMAC-CIDC/cidc-schemas/blob/fdebd19adc1907097ac59d476406e8b20314985c/cidc_schemas/schemas/artifacts/artifact_core.json#L32
I think this would lead template tests to fail if we ever create a new template schema that includes `[` or `]` in the generated GCS URIs.
Here's an example of a regex validation check: https://github.com/CIMAC-CIDC/cidc-schemas/blob/fdebd19adc1907097ac59d476406e8b20314985c/cidc_schemas/schemas/sample.json#L12

2020-12-15 21:49 UTC, jacoblurye commented on cidc_schemas/template.py
> +
(I know I "requested changes", but totally open to arguments against this suggestion)

2020-12-15 21:54 UTC, scvannost commented on cidc_schemas/template.py
> +
I put it here, as what is being substituted into the gcs_uri format could also contain brackets, like the run ID for mIF does

I'm not sure that just adding a constraint to `artifact_core#object_url` will handle that

2020-12-16 13:05 UTC, jacoblurye commented on cidc_schemas/template.py
> +
It would, because the full GCS URI (including user input) is what gets checked by `artifact_core#object_url` as part of overall JSON schema validation after the xlsx metadata has been `prismify`ed into a JSON blob.

2020-12-17 15:52 UTC, scvannost commented on cidc_schemas/template.py
> +
Ah yes, here? https://github.com/CIMAC-CIDC/cidc-api-gae/blob/master/cidc_api/resources/upload_jobs.py#L304

2020-12-17 15:57 UTC, scvannost commented on cidc_schemas/template.py
> +
but what if the actual run id used in the file is for eg `[aaaa, bbbb]`  as suggested here: https://github.com/CIMAC-CIDC/cidc-schemas/blob/master/template_examples/csvs/mif_template__Legend.csv#L17
and how it is for the actual upload already in a staging bucket.

2020-12-17 16:14 UTC, jacoblurye commented on cidc_schemas/template.py
> +
Actually, here: https://github.com/CIMAC-CIDC/cidc-api-gae/blob/e4d60e17a5f0e89bc4a0b9b83ef2f41c1a69136f/cidc_api/resources/upload_jobs.py#L343
and then here: https://github.com/CIMAC-CIDC/cidc-schemas/blob/fdebd19adc1907097ac59d476406e8b20314985c/cidc_schemas/prism/merger.py#L381

Ah, yeah - I see now how it's better to change things on the fly the way it currently is in your PR, since this will only impact the URL we use for GCS storage and we don't want to outlaw run ids that have square brackets in them. Let's go with what you have.

2020-12-17 17:08 UTC, jacoblurye approved these changes

2020-12-17 17:08 UTC, jacoblurye commented on tests/test_template.py
> +    changes, files = _FieldDef(**prop_def).process_value("baz", {}, {})
```suggestion
    changes, files = _FieldDef(**prop_def).process_value("baz.bar", {}, {})
```

2020-12-17 17:48 UTC, merged